### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by vanceism7** [purescript-python/installer#5]
The last command in the setup instructions is failing
`pip install git+https://github.com/purescript-python/installer`

Here's the error:
```
Collecting git+https://github.com/purescript-python/installer
  Cloning https://github.com/purescript-python/installer to /run/user/1000/pip-req-build-ehxhks06
  Running command git clone -q https://github.com/purescript-python/installer /run/user/1000/pip-req-build-ehxhks06
    ERROR: Command errored out with exit status 1:
     command: /nix/store/aw85aijllnc5spk2fqbivygrhx6x7411-python3-3.7.6/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/run/user/1000/pip-req-build-ehxhks06/setup.py'"'"'; __file__='"'"'/run/user/1000/pip-req-build-ehxhks06/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /run/user/1000/pip-req-build-ehxhks06/pip-egg-info
         cwd: /run/user/1000/pip-req-build-ehxhks06/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

(I included the warning just to show my pip version)

It looks to me like we need to install `setuptools` before the script python script can run correctly?

**Comment by thautwarm** [comment]
Hi, this is actually subtle..
Almost all python setup files depend on the `setuptools`, which shall be a standard library of Python.
If you want to use `pip` and install python packages from sources, you're supposed to have `setuptools`.

To solve this, maybe we just add a note in [the README here](https://github.com/purescript-python/purescript-python), saying "please make sure setuptools is installed in your python environment".

**Comment by thautwarm** [comment]
It seems this error is caused by Python 2? PureScript Python doesn't support Python 2 yet.

**Comment by vanceism7** [comment]
Hmm, Im using python 3.7 - I don't believe this is a python 2 issue. Is there no way to ensure `setuptools` is installed using a script?

Perhaps something like this:
https://stackoverflow.com/questions/9044040/is-there-a-way-for-pip-to-install-only-new-dependencies-in-an-updated-requiremen

**Comment by thautwarm** [comment]
Yep, using `requirements.txt` may work. Could you make a PR?

**Comment by thautwarm** [comment]
I'm not sure if `pip` is depending on `setuptools`, as the latter is really essential.

**Comment by vanceism7** [comment]
Yea, I can do that :+1:. I don't think pip depends on setup tools, it seems pip itself is running ok. Ill make a PR and test it out to make sure

**Comment by vanceism7** [comment]
After looking into this more, I see what you're saying about `setuptools` being basically part of the standard library. I think you're original suggestion is probably the best solution here: I'll just put some notes in the `README` about a set of prerequisite packages needed for the install to work
